server:
  servlet:
    context-path: /api

spring:
  datasource:
    url: "jdbc:${DATABASE_HOST}"
    username: "${DATABASE_USER}"
    password: "${DATABASE_PASSWORD}"
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true


jwt:
  signerKey: "${SIGNER_KEY}"

allowed: "${ALLOWED_ORIGIN}"