server:
  post: 8080
  servlet:
    context-path: /api

spring:
  datasource:
    url: "jdbc:${DATABASE_HOST}"
    username: "${DATABASE_USER}"
    password: "${DATABASE_PASSWORD}"
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  signerKey: "RofoSqL4PFeQxQ8Oo21rxkVxypwLYwXp21pCua9BK/v6bevAReQYwLKhuODeyvBr"