server:
  servlet:
    context-path: /api

spring:
  datasource:
    url: "${DATABASE_HOST}"
    username: "${DATABASE_USER}"
    password: "${DATABASE_PASSWORD}"


  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: "${GOOGLE_CLIENT_ID}"
            client-secret: "${GOOGLE_CLIENT_SECRET}"
            scope: openid,profile,email
            redirect-uri: "${REDIRECT_GOOGLE_LOGIN}"

firebase:
  type: service_account
  project-id: "${FIREBASE_PROJECT_ID}"
  private-key-id: "${FIREBASE_PRIVATE_KEY_ID}"
  private-key: "${FIREBASE_PRIVATE_KEY}"
  client-email: "${FIREBASE_CLIENT_EMAIL}"
  client-id: "${FIREBASE_CLIENT_ID}"
  auth-uri: https://accounts.google.com/o/oauth2/auth
  token-uri: https://oauth2.googleapis.com/token
  auth-provider-x509-cert-url: https://www.googleapis.com/oauth2/v1/certs
  client-x509-cert-url: "${FIREBASE_CLIENT_X509_CERT_URL}"
  universe-domain: googleapis.com

jwt:
  signerKey: "${SIGNER_KEY}"

allowed: "${ALLOWED_ORIGIN}"